<a href="https://colab.research.google.com/github/babinraaz/PythonClass/blob/master/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day *8*
2. polymorphism

In [2]:
#polymorphism
# we get different behavious after calling from different objects
class A:
  def explore(self):
    print("explore() from class A")
class B:
  def explore(self):
    print("Explore () from class B ")

a_obj = A()
b_obj = B()

a_obj.explore()

explore() from class A


### NumPy


In [ ]:
#NumPy is a powerful python library

#install numPy
#!pip install numpy
#import numpy or import numpy as np  
#numpy.__version__
#

In [8]:
#arrays => superfast ==> compared to list
# one dimensional array

import numpy as np

np.array([1,2,3,4,5])     #same type of data
arr1d = np.array([1,2,3,4,5])
type(arr1d)   #type
arr1d.shape
arr1d.ndim    #dimension

arr2d = np.array([[0,3], [-5, 7], [99, 4]])
arr2d
arr2d.ndim    #dimesion

arr2d.dtype   #data type



dtype('int64')

In [12]:
import numpy as np

#multi-dimensional arrray

np.zeros(6)
#array([0., 0., 0., 0., 0., 0.])

np.ones(6)
#array([1., 1., 1., 1., 1., 1.])

np.zeros=(2,3)

In [18]:
#accessing array elements/items
#np.random.random((2,3))
arr_ = np.random.randint(1,10, size =(2,3))
arr_[0]
arr_[:,1]   #to get all values from row or column ':'

array([8, 4])

In [30]:
#universal functions

import numpy as np
arr_ = np.arange(1,10)
arr_ ** 2
-arr_
np.sum(arr_)
np.power(arr_,4)

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])